USE [master]
RESTORE DATABASE [SERDONRECORTES] FROM  DISK = N'G:\copy_to_restore\serdonrecortes\BkpSERDONRECORTES.bak' WITH  FILE = 1,  
MOVE N'SERDONRECORTES' TO N'G:\BANCOS\DADOS\SERDONRECORTES_01.mdf',  
MOVE N'SERDONRECORTES_log' TO N'L:\BANCOS\LOGS\SERDONRECORTES_log_01.ldf',  
NORECOVERY, NOUNLOAD,  STATS = 5
go
RESTORE database [SERDONRECORTES] FROM  DISK = N'G:\copy_to_restore\serdonrecortes\BkpSERDONRECORTESDiff.bak' WITH  FILE = 1,  
MOVE N'SERDONRECORTES' TO N'G:\BANCOS\DADOS\SERDONRECORTES_01.mdf',  
MOVE N'SERDONRECORTES_log' TO N'L:\BANCOS\LOGS\SERDONRECORTES_log_01.ldf',  
NORECOVERY, NOUNLOAD, replace, STATS = 5
go
RESTORE LOG [SERDONRECORTES] FROM  DISK = N'G:\copy_to_restore\serdonrecortes\BkpLG_SERDONRECORTESFri.bak' WITH  FILE = 1, NORECOVERY, NOUNLOAD,  STATS = 5

RESTORE LOG [SERDONRECORTES] FROM  DISK = N'G:\copy_to_restore\serdonrecortes\BkpLG_SERDONRECORTESFri.bak' WITH  FILE = 2, NORECOVERY, NOUNLOAD,  STATS = 5

RESTORE LOG [SERDONRECORTES] FROM  DISK = N'G:\copy_to_restore\serdonrecortes\BkpLG_SERDONRECORTESFri.bak' WITH  FILE = 3, NORECOVERY, NOUNLOAD,  STATS = 5

RESTORE LOG [SERDONRECORTES] FROM  DISK = N'G:\copy_to_restore\serdonrecortes\BkpLG_SERDONRECORTESFri.bak' WITH  FILE = 4, NORECOVERY, NOUNLOAD,  STATS = 5

RESTORE LOG [SERDONRECORTES] FROM  DISK = N'G:\copy_to_restore\serdonrecortes\BkpLG_SERDONRECORTESFri.bak' WITH  FILE = 5, NORECOVERY, NOUNLOAD,  STATS = 5

RESTORE LOG [SERDONRECORTES] FROM  DISK = N'G:\copy_to_restore\serdonrecortes\BkpLG_SERDONRECORTESFri.bak' WITH  FILE = 6, NORECOVERY, NOUNLOAD,  STATS = 5

RESTORE LOG [SERDONRECORTES] FROM  DISK = N'G:\copy_to_restore\serdonrecortes\BkpLG_SERDONRECORTESFri.bak' WITH  FILE = 7, NORECOVERY, NOUNLOAD,  STATS = 5

RESTORE LOG [SERDONRECORTES] FROM  DISK = N'G:\copy_to_restore\serdonrecortes\BkpLG_SERDONRECORTESFri.bak' WITH  FILE = 8, NORECOVERY, NOUNLOAD,  STATS = 5

RESTORE LOG [SERDONRECORTES] FROM  DISK = N'G:\copy_to_restore\serdonrecortes\BkpLG_SERDONRECORTESFri.bak' WITH  FILE = 9, NORECOVERY, NOUNLOAD,  STATS = 5

RESTORE LOG [SERDONRECORTES] FROM  DISK = N'G:\copy_to_restore\serdonrecortes\BkpLG_SERDONRECORTESFri.bak' WITH  FILE = 10, NORECOVERY, NOUNLOAD,  STATS = 5

RESTORE LOG [SERDONRECORTES] FROM  DISK = N'G:\copy_to_restore\serdonrecortes\BkpLG_SERDONRECORTESFri.bak' WITH  FILE = 11, NORECOVERY, NOUNLOAD,  STATS = 5

RESTORE LOG [SERDONRECORTES] FROM  DISK = N'G:\copy_to_restore\serdonrecortes\BkpLG_SERDONRECORTESFri.bak' WITH  FILE = 12, NORECOVERY, NOUNLOAD,  STATS = 5

RESTORE LOG [SERDONRECORTES] FROM  DISK = N'G:\copy_to_restore\serdonrecortes\BkpLG_SERDONRECORTESFri.bak' WITH  FILE = 13, NORECOVERY, NOUNLOAD,  STATS = 5

RESTORE LOG [SERDONRECORTES] FROM  DISK = N'G:\copy_to_restore\serdonrecortes\BkpLG_SERDONRECORTESFri.bak' WITH  FILE = 14, NOUNLOAD,  STATS = 5

